version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kiyingi_denis_ftb_dev_app
    container_name: kiyingi_denis_ftb_dev_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: kiyingi_denis_ftb_dev_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: kiyingi_denis_ftb_dev_app
    container_name: kiyingi_denis_ftb_dev_app_test
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    entrypoint: ["./vendor/bin/phpunit", "--testdox"]

networks:
  app-network:
    driver: bridge
